import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./Components/Navbar";
import "./globals.css";
import { ClientCookiesProvider } from "./Components/ClientCookiesProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ClientCookiesProvider>
                <body className={inter.className}>
                    <NavBar />
                    {children}
                    <div className="h-20"></div>
                </body>
            </ClientCookiesProvider>
        </html>
    );
}
